sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
env:
  - NODE_ENV=development
install:
  - npm install
  - cp package.json test/mock-project/package.json
  - cd test/mock-project
  - npm install
  - npm install gulp
  - cd ../..
  - npm install mocha -g
  - npm install gulp-cli -g
before_script:
  - npm prune
script:
  - mocha
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/