sudo: false
language: node_js
node_js:
    - '0.12'
env:
    - NODE_ENV=development
install:
    - npm install
    - cp package.json test/mock-project/package.json
    - cd test/mock-project
    - npm install
    - npm install gulp
    - cd ../..
    - npm install mocha -g
    - npm install gulp-cli -g
script:
    - mocha
git:
  depth: 1
