os: Visual Studio 2015
platform: x64
environment:
  NODE_ENV: development
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
# Don't actually build.
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json
